spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update